version: '3.3'

services:
  database:
    build: ./mysql-scripts
    restart: always
    env_file:
      - ./mysql-scripts/.env
    # ports:
    #   - "3306:3306"
    volumes:
      - mysql-scripts:/docker-entrypoint-initdb.d
    networks:
      - projeto_final_network

  backend:
    build: ./backend
    depends_on:
      - database
    ports:
      - "5000:5000"
    restart: always
    env_file:
      - ./backend/.env
    networks:
      - projeto_final_network


  frontend:
    depends_on:
      - backend
    build: ./frontend
    ports: 
      - "3000:3000"
    restart: always
    networks:
      - projeto_final_network


networks:
  projeto_final_network:

volumes:
  mysql-scripts: {}
